data:
  raw_csv: data/raw/zomato_df_final_data.csv
  geojson: data/external/sydney.geojson
  processed_csv: data/processed/zomato_processed.csv

features:
  keep_columns: ["cost", "rating_number", "votes"]

model:
  type: "LogisticRegression"
  target: "is_high_cost"
  cost_threshold: 60.0
  random_state: 42
  max_iter: 200

reports:
  metrics_file: reports/metrics.json
  fig_hist: reports/figures/cost_hist.png